variables:
  GIT_SUBMODULE_STRATEGY: recursive
  AWS_REGION: "ap-south-1"
  AWS_ACCOUNT_ID: "043309339851"
  BUCKET_NAME: "vkrr-lambda-artifacts"

before_script:
  - export SERVERLESS_ACCESS_KEY="$SERVERLESS_ACCESS_KEY"
  - export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
  - export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
  - export AWS_REGION="ap-south-1"
  - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
  - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
  - aws configure set region "$AWS_REGION"

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - main
    - staging
    - development
  script:
    - echo "Installing dependencies..."
    - NODE_ENV=development npm install

    - echo "Building NestJS application..."
    - npm run build  # Build application
  artifacts:
    paths:
      - dist/
      - node_modules/

deploy:
  stage: deploy
  only:
    - main
    - staging
    - development
  script:
    - |
      # Determine the stage based on the branch
      if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        STAGE="production"
      elif [[ "$CI_COMMIT_BRANCH" == "staging" ]]; then
        STAGE="staging"
      elif [[ "$CI_COMMIT_BRANCH" == "development" ]]; then
        STAGE="development"
      else
        echo "Unknown branch, exiting..."
        exit 1
      fi

    - echo "Deploying to $STAGE environment..."
    - serverless deploy --stage $STAGE
