service: xkart

configValidationMode: error

custom:
  prune:
    automatic: true
    number: 2
  addHttpOffline:
    dev: []
    local:
      - httpApi:
          method: '*'
          path: '/{proxy+}'
  serverless-offline:
    httpPort: 4000

  domainMapping:
    production: api.xkartindia.com
    staging: staging-api.xkartindia.com
  customDomain:
    domainName: ${self:custom.domainMapping.${self:provider.stage}}
    stage: ${self:provider.stage}
    basePath: ''
    certificateName: 'xkartindia.com'
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: REGIONAL
    securityPolicy: tls_1_2
    apiType: http
    autoDomain: true

  frontendUrl:
    production: 'https://xkartindia.com'
    staging: 'https://staging.xkartindia.com'

  ssmParams:
    production:
      mongo: "/xkart/production/MONGO_URI"
      redis: "/xkart/production/REDIS_URI"
    staging:
      mongo: "/xkart/staging/MONGO_URI"
      redis: "/xkart/staging/REDIS_URI"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: ${opt:stage, 'production'}
  deploymentMethod: direct
  logRetentionInDays: 7
  role: arn:aws:iam::043309339851:role/nestjs-lambda-role
  environment:
    NODE_ENV: ${self:provider.stage, 'production'}
    FRONTEND_URL: ${self:custom.frontendUrl.${self:provider.stage}, 'http://localhost:5173'}
    MONGO_URI: ${ssm:${self:custom.ssmParams.${self:provider.stage}.mongo}}
    REDIS_URI: ${ssm:${self:custom.ssmParams.${self:provider.stage}.redis}}

  vpc:
    securityGroupIds:
      - sg-0fdba5049024ab559
    subnetIds:
      - subnet-03fe12f4f9787e22a
      - subnet-02b3abba35cd77a6e
      - subnet-04a18e63cfbb316f2

package:
  individually: true
  patterns:
    - '!src/**'
    - '!node_modules/**'
    - '!*.md'
    - 'package.json'
    - 'dist/**'
    - 'src/schema.gql'

functions:
  api:
    handler: dist/main.handler
    memorySize: 512
    timeout: 30
    url: true
    events:
      - httpApi:
          path: "/{proxy+}"
          method: "*"

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-domain-manager
